const mutations = {
  // root
  SET_USER_ID: 'SET_USER_ID',
  SET_USER_MEMBERSHIPS: 'SET_USER_MEMBERSHIPS',
  SET_PROGRESS: 'SET_PROGRESS',

  // settings
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_ITEM_SIZE: 'SET_ITEM_SIZE',
  SET_ITEM_SPACING: 'SET_ITEM_SPACING',

  // membership
  SET_ID: 'SET_ID',
  SET_NAME: 'SET_NAME',
  SET_PLATFORM: 'SET_PLATFORM',
  SET_VAULT: 'SET_VAULT',
  SET_ACCOUNT_ITEMS: 'SET_ACCOUNT_ITEMS',
  SET_ITEMS: 'SET_ITEMS',
  SET_CHARACTER: 'SET_CHARACTER',
  SET_ACTIVE_CHARACTER: 'SET_ACTIVE_CHARACTER',
  SET_STORAGE_TYPE: 'SET_STORAGE_TYPE',
  RESET: 'RESET',
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
  SET_SEARCH_ACTIVE: 'SET_SEARCH_ACTIVE',
};

const actions = {
  // membership
  FETCH_PROFILE: 'FETCH_PROFILE',
  PROCESS_PROFILE: 'PROCESS_PROFILE',
  GET_DEFINITIONS: 'GET_DEFINITIONS',
  PROCESS_CHARACTERS: 'PROCESS_CHARACTERS',
  PROCESS_INVENTORIES: 'PROCESS_INVENTORIES',
  PROCESS_PROFILE_INVENTORY: 'PROCESS_PROFILE_INVENTORY',
  PROCESS_CHARACTERS_INVENTORIES: 'PROCESS_CHARACTERS_INVENTORIES',
  SET_CHARACTER: 'SET_CHARACTER',
};

const Types = {
  ...mutations,
  ...actions,
};

export { Types as default };
